[project]
name = "doc-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Syed Badi Uz Zaman", email = "syedbadi.shah66@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
doc-agent = "doc_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
